### ISSUE TITLE
hardis:doc:project2markdown linter errors leading to failure in .md generation for apex classes and triggers

### ISSUE THREAD

**Issue by maksym-petrov-ct** [hardisgroupcom/sfdx-hardis#1604]
After launching `sf hardis:doc:project2markdown` there are log lines like this:
```
Using temp directory /tmp/sfdx-hardis-ml4hv
Error generating Apex documentation: [
  "Error(s) occurred while parsing files. Please review the following issues:",
  "Source file: force-app/main/default/classes/my_class.cls\nException: Error parsing Apex Body. Line 378:52 - missing ';' at '('\n"
]
```
First of all, I have to tell  that all class files and triggers were just retrieved from the org and are deployable. 
The line 378 in question is nothing suspicious:
```
    private static void AdjustSL_SE_Date_FromJanuary(...
```
Offset :52  points to 'r' in word January above.

**It ends up not generating any apex or trigger .md files. Objects, flows, etc are generated.**

If the my_class.cls is deleted along with it's -meta.xml, then another set of errors for triggers appears, like this:
```
"Source file: force-app/main/default/triggers/Account_trigger_vod.trigger\nException: Error parsing Apex Body. Line 1:39 - extraneous input 'bulk' expecting '('\n",
```

Here is the 1st line of example trigger:
```
trigger Account_trigger_vod on Account bulk (before delete, after delete) {
```
I tried to delete all triggers mentioned in error message. It leads to apex .md files are generated, **but triggers .md are still not generated,** despite no visible errors.
The generation time for `sf hardis:doc:project2markdown` is always 6-7 minutes in my project (no AI integration) and is unrelated to errors above. 

```
node --version
v24.11.1

sf --version
@salesforce/cli/2.114.5 wsl-x64 node-v24.11.1

sf plugins
@salesforce/commerce 252.0.0
@salesforce/sfdx-scanner 4.2.0 (latest-beta)
code-analyzer 5.0.0 (5.0.0)
community 3.2.32 (3.2.32)
dev 2.5.1 (2.5.1)
packaging 2.23.5
sfdmu 4.38.0
sfdx-git-delta 6.24.0
sfdx-hardis 6.14.2
signups 2.6.43 (2.6.43)
texei-sfdx-plugin 2.8.3
```

**Comment by nvuillam** [comment]
@maksym-petrov-ct > sfdx-hardis relies on https://github.com/cesarParra/apexdocs to generate apex doc, so the parsing problem is to address there

cc @cesarParra

**Comment by cesarParra** [comment]
The trigger issue should be addressed in the latest version (3.17.0), though I wasn't able to replicate the Apex parsing issue. Please feel free to open an issue in https://github.com/cesarParra/apexdocs/issues to discuss further.

**Comment by maksym-petrov-ct** [comment]
@cesarParra issue created: https://github.com/cesarParra/apexdocs/issues/307
Thanks ☺

**Comment by cesarParra** [comment]
Version 3.20.0 has been released with the full fix (not just addressing the `bulk` keyword as before).

**Comment by maksym-petrov-ct** [comment]
Hi @nvuillam 
I revisited command  `hardis:doc:project2markdown` and still see that triggers are not counted as code, only apex classes and LWC are there in my results.  My legacy project contains a lot of logic in triggers. Is there a way to add them ?

**Comment by nvuillam** [comment]
I have a webinar next week for London admin group so i'll work on doc features this weekend, i'll try to was this :)

**Comment by maksym-petrov-ct** [comment]
Hi @nvuillam 
looks like triggers are now listed in http://127.0.0.1:8000/apex/  (all classes page) but if i click to one of triggers, then getting `404 - Not found`.  is it expected for now ?

**Comment by nvuillam** [comment]
I've not implemented it yet 🥹🥹

**Comment by nvuillam** [comment]
Would you like to ? :)

**Comment by maksym-petrov-ct** [comment]
It may be a long journey for me. I am not skilled in TypeScript so far☺
